const $=id=>document.getElementById(id);
const canvas=$('scene'),ctx=canvas.getContext('2d');
const sample=document.createElement('canvas');sample.width=160;sample.height=90;
const sc=sample.getContext('2d',{willReadFrequently:true});
let targetHue=178,selectingColor=false,lastDetection=null;
let source='sim',scenario='roam',start=performance.now(),paused=false,stream=null;
let generation=0,pendingReset=false,lastAction='',visibleSamples=0,centeredSamples=0;
let streak=0,score=0,awarded=false,lastVisible=true,records=[];
const cameraAdapter={pan:0,rotate(d){this.pan=Math.max(-45,Math.min(45,this.pan+d*3));},stop(){},reset(){this.pan=0;}};
function log(text){const li=document.createElement('li');li.textContent=new Date().toLocaleTimeString('zh-CN',{hour12:false})+' · '+text;const el=$('events');if(el.children[0]?.textContent.startsWith('就绪'))el.innerHTML='';el.prepend(li);while(el.children.length>8)el.lastChild.remove();}
function rect(x,y,w,h,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function drawSim(t){ctx.fillStyle='#263f3d';ctx.fillRect(0,0,800,450);ctx.fillStyle='#314e49';ctx.fillRect(0,300,800,150);ctx.strokeStyle='#406057';ctx.lineWidth=1;for(let x=0;x<800;x+=100){ctx.beginPath();ctx.moveTo(400,300);ctx.lineTo(x,450);ctx.stroke();}rect(52,70,175,130,8,'#567168');rect(60,78,159,114,3,'#8b9c7e');ctx.strokeStyle='#425e52';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(138,78);ctx.lineTo(138,192);ctx.stroke();rect(82,265,207,72,15,'#829681');rect(70,302,230,47,12,'#6b806c');rect(485,285,65,22,8,'#a3a489');ctx.fillStyle='#92957b';ctx.fillRect(496,304,6,50);ctx.fillRect(536,304,6,50);
 let x=355+Math.sin(t*.25)*165;if(scenario==='left')x=205;if(scenario==='right')x=550;if(scenario==='hide')x=690;
 ctx.fillStyle='#2cc6c2';ctx.beginPath();ctx.arc(x,225+Math.sin(t*1.2)*10,23,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d6dfcb';ctx.font='12px sans-serif';ctx.fillText('LIVING ROOM / 合成测试画面',24,30);
}
function mask(){ctx.fillStyle='#162b2b';ctx.fillRect(608,0,192,450);ctx.strokeStyle='#35504a';ctx.lineWidth=1;for(let y=0;y<600;y+=18){ctx.beginPath();ctx.moveTo(608,y);ctx.lineTo(800,y-120);ctx.stroke();}ctx.fillStyle='#c0cdb8';ctx.font='14px sans-serif';ctx.fillText('隐私区 · 不分析',641,220);}
function render(now){if(!paused){if(source==='webcam'&&$('webcam').readyState>=2)ctx.drawImage($('webcam'),0,0,800,450);else drawSim((now-start)/1000);mask();sc.drawImage(canvas,0,0,160,90);if(lastDetection?.visible){const [x,y,w,h]=lastDetection.box;ctx.strokeStyle='#bdff54';ctx.lineWidth=2;ctx.strokeRect(x*800,y*450,w*800,h*450);ctx.fillStyle='#bdff54';ctx.font='12px sans-serif';ctx.fillText('颜色目标',x*800,Math.max(16,y*450-7));}const center=400+cameraAdapter.pan/45*250;ctx.strokeStyle='#dceab080';ctx.lineWidth=2;ctx.strokeRect(center-48,70,96,310);ctx.fillStyle='#dceab0';ctx.font='11px sans-serif';ctx.fillText('模拟取景中心',center-36,399);}requestAnimationFrame(render);}
function feature(){const p=sc.getImageData(0,0,160,90).data;const d=ColorTracker.detect(p,160,90,source==='sim'?178:targetHue,121);lastDetection=d;const pos=d.visible?d.cx*2-1:0;return{visible:d.visible,x:Math.max(-1,Math.min(1,pos-cameraAdapter.pan/45*.625))};}
function targetChanged(){lastDetection=null;generation++;pendingReset=true;window.dispatchEvent(new Event('fly-reset'));cameraAdapter.reset();clearScore();}
$('pickColor').onclick=()=>{if(source!=='webcam'){$('detectorHint').textContent='请先接入本机摄像头，再点击物体选择颜色。';return;}if(paused){$('detectorHint').textContent='请先继续画面，再选择颜色。';return;}selectingColor=true;canvas.style.cursor='crosshair';$('detectorHint').textContent='点击画面左侧物体的纯色部分，避开高光、阴影和右侧隐私区。';};
$('defaultColor').onclick=()=>{targetHue=178;selectingColor=false;canvas.style.cursor='default';$('colorSwatch').style.background='hsl(178 70% 50%)';$('detectorHint').textContent='已恢复青色。建议用鲜亮的青色卡纸或毛巾。';targetChanged();};
canvas.addEventListener('click',e=>{if(!selectingColor||source!=='webcam')return;const r=canvas.getBoundingClientRect(),x=Math.min(159,Math.max(0,Math.floor((e.clientX-r.left)/r.width*160))),y=Math.min(89,Math.max(0,Math.floor((e.clientY-r.top)/r.height*90)));const c=ColorTracker.pick(sc.getImageData(0,0,160,90).data,160,90,x,y,121);if(c.error){$('detectorHint').textContent=c.error;return;}targetHue=c.h;selectingColor=false;canvas.style.cursor='default';$('colorSwatch').style.background=`hsl(${targetHue} 70% 50%)`;$('detectorHint').textContent='已选颜色：追踪最大连续色块，不区分同色物品的身份。';targetChanged();log('更新摄像头追踪颜色');});
function updatePlay(f){if(!f.visible){streak=0;awarded=false;$('playTitle').textContent='它暂时看不到目标';$('playText').textContent='目标消失或进入隐私区后停止转动；重新出现时继续寻找。';if(lastVisible)log('目标不可见 → 停止转动');lastVisible=false;return;}if(!lastVisible)log('目标重新出现 → 恢复感知');lastVisible=true;visibleSamples++;if(Math.abs(f.x)<.12){centeredSamples++;streak++;}else{streak=0;awarded=false;}$('focus').textContent=Math.round(centeredSamples/visibleSamples*100)+'%';if(streak>=3&&!awarded){awarded=true;score++;$('score').textContent=score;$('playTitle').textContent='找到啦，再带它去另一边';$('playText').textContent='连续三个采样保持居中，本轮得到一次互动记录。';$('payload').textContent=JSON.stringify({event:'目标持续居中',time:new Date().toLocaleTimeString('zh-CN'),controller:$('mode').value,pan:cameraAdapter.pan,source},null,2);log('持续居中 → 记录一次互动');}else if(streak<3){$('playTitle').textContent='小飞正在找目标';$('playText').textContent='观察左右神经活动，看取景中心能否靠近目标。';}}
async function tick(){if(paused)return;const f=feature(),token=generation,mode=$('mode').value;$('observation').textContent=f.visible?`已锁定颜色区域 · 占有效画面 ${(lastDetection.area*100).toFixed(1)}%`:lastDetection.reason;try{if(pendingReset){const r=await fetch('/api/reset',{method:'POST'});if(!r.ok)throw new Error();pendingReset=false;}const res=await fetch('/api/step',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({x:f.x,visible:f.visible,mode})});if(!res.ok)throw new Error();const r=await res.json();if(token!==generation||paused)return;window.dispatchEvent(new CustomEvent('fly-spikes',{detail:r}));$('connection').textContent='● 果蝇网络运行中 · CPU';$('leftRate').textContent=r.left.toFixed(1);$('rightRate').textContent=r.right.toFixed(1);$('leftMeter').value=r.left;$('rightMeter').value=r.right;cameraAdapter.rotate(r.action);$('pan').textContent=`模拟朝向 ${cameraAdapter.pan}°`;const a=r.action<0?'向左关注':r.action>0?'向右关注':'保持朝向';$('action').textContent=a;$('injection').textContent=`输入 ${r.injection} · 输出 ${mode==='fly'?'DNa02 左右活动差':mode==='baseline'?'普通位置规则':'动作断开'}`;$('compute').textContent=`本轮神经计算 ${r.compute_ms} ms / 25 步`;if(a!==lastAction){lastAction=a;log(`${$('mode').selectedOptions[0].textContent} → ${a}`);}updatePlay(f);records.push({time:Date.now(),mode,source,scene:scenario,x:f.x,visible:f.visible,action:r.action,left:r.left,right:r.right,compute_ms:r.compute_ms});if(records.length>3000)records.shift();}catch(e){$('connection').textContent='果蝇服务未连接 · 无神经控制';$('action').textContent='服务异常 · 停止模拟转动';cameraAdapter.stop();}}
async function loop(){try{await tick();}finally{setTimeout(loop,500);}}
function clearScore(){visibleSamples=0;centeredSamples=0;streak=0;score=0;awarded=false;$('focus').textContent='0%';$('score').textContent='0';$('payload').textContent='等待一次持续居中…';}
function changeScene(name){lastDetection=null;selectingColor=false;canvas.style.cursor='default';scenario=name;source='sim';if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}$('sourceLabel').textContent='模拟摄像头';$('cameraError').textContent='';start=performance.now();generation++;pendingReset=true;window.dispatchEvent(new Event('fly-reset'));cameraAdapter.reset();streak=0;awarded=false;for(const b of document.querySelectorAll('[data-scene]'))b.classList.toggle('selected',b.dataset.scene===name);log('切换场景：'+document.querySelector(`[data-scene="${name}"]`).textContent);}
for(const b of document.querySelectorAll('[data-scene]'))b.onclick=()=>changeScene(b.dataset.scene);
$('simButton').onclick=()=>changeScene('roam');
$('pauseButton').onclick=()=>{paused=!paused;window.dispatchEvent(new CustomEvent('fly-pause',{detail:paused}));$('pauseButton').textContent=paused?'继续':'暂停';if(paused){generation++;cameraAdapter.stop();}};
$('mode').onchange=()=>{generation++;pendingReset=true;window.dispatchEvent(new Event('fly-reset'));cameraAdapter.reset();clearScore();log('控制方式切换：'+$('mode').selectedOptions[0].textContent);};
$('resetButton').onclick=()=>{paused=false;window.dispatchEvent(new CustomEvent('fly-pause',{detail:false}));$('pauseButton').textContent='暂停';clearScore();records=[];changeScene('roam');$('events').innerHTML='';log('新的一局开始');};
$('cameraButton').onclick=async()=>{try{if(stream)stream.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({video:{width:800,height:450},audio:false});$('webcam').srcObject=stream;await $('webcam').play();source='webcam';lastDetection=null;paused=false;window.dispatchEvent(new CustomEvent('fly-pause',{detail:false}));$('pauseButton').textContent='暂停';generation++;pendingReset=true;window.dispatchEvent(new Event('fly-reset'));cameraAdapter.reset();clearScore();$('sourceLabel').textContent='本机摄像头 · 颜色追踪';$('cameraError').textContent='';for(const b of document.querySelectorAll('[data-scene]'))b.classList.remove('selected');log('本机摄像头启用：只向本地服务传目标位置');}catch(e){$('cameraError').textContent='摄像头未能启用，可继续使用模拟画面。';}};
$('exportButton').onclick=()=>{const blob=new Blob([JSON.stringify({note:'演示样本；不同场景不可直接比较性能；无视频或图像',records},null,2)],{type:'application/json'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download='living-lens-metrics.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
window.addEventListener('pagehide',()=>stream?.getTracks().forEach(t=>t.stop()));
requestAnimationFrame(render);setTimeout(loop,300);
