/* Color-region tracking, not semantic object recognition. Shared by browser and tests. */
(function(root){
function hsv(r,g,b){r/=255;g/=255;b/=255;const v=Math.max(r,g,b),d=v-Math.min(r,g,b);let h=0;if(d){if(v===r)h=((g-b)/d+6)%6;else if(v===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;}return {h,s:v?d/v:0,v};}
function hueDistance(a,b){return Math.abs((a-b+540)%360-180);}
function pick(data,w,h,x,y,limit){if(x>=limit)return {error:'右侧是隐私区，请点击左侧物体。'};const colors=[];for(let yy=Math.max(0,y-2);yy<=Math.min(h-1,y+2);yy++)for(let xx=Math.max(0,x-2);xx<=Math.min(limit-1,x+2);xx++){let i=(yy*w+xx)*4;const c=hsv(data[i],data[i+1],data[i+2]);if(c.s>=.45&&c.v>=.10)colors.push(c);}if(colors.length<5)return {error:'这里颜色太灰或太暗，请选物体上颜色鲜明、没有反光的位置。'};let sx=0,sy=0;for(const c of colors){sx+=Math.cos(c.h*Math.PI/180);sy+=Math.sin(c.h*Math.PI/180);}if(Math.hypot(sx,sy)/colors.length<.65)return {error:'这里混合了多种颜色，请点物体内部的纯色区域。'};return {h:(Math.atan2(sy,sx)*180/Math.PI+360)%360};}
function detect(data,w,h,target,limit=w){const accepted=new Uint8Array(w*h),seen=new Uint8Array(w*h);let total=0;for(let y=0;y<h;y++)for(let x=0;x<limit;x++){const i=(y*w+x)*4,c=hsv(data[i],data[i+1],data[i+2]);if(c.s>=.45&&c.v>=.10&&hueDistance(c.h,target)<=24){accepted[y*w+x]=1;total++;}}
let best=null;for(let y=0;y<h;y++)for(let x=0;x<limit;x++){const start=y*w+x;if(!accepted[start]||seen[start])continue;const queue=[start];seen[start]=1;let sx=0,sy=0,minX=x,maxX=x,minY=y,maxY=y;for(let k=0;k<queue.length;k++){const n=queue[k],xx=n%w,yy=Math.floor(n/w);sx+=xx;sy+=yy;minX=Math.min(minX,xx);maxX=Math.max(maxX,xx);minY=Math.min(minY,yy);maxY=Math.max(maxY,yy);for(const [nx,ny] of [[xx-1,yy],[xx+1,yy],[xx,yy-1],[xx,yy+1]]){if(nx<0||nx>=limit||ny<0||ny>=h)continue;const nn=ny*w+nx;if(accepted[nn]&&!seen[nn]){seen[nn]=1;queue.push(nn);}}}if(!best||queue.length>best.count)best={count:queue.length,cx:(sx/queue.length+.5)/w,cy:(sy/queue.length+.5)/h,box:[minX/w,minY/h,(maxX-minX+1)/w,(maxY-minY+1)/h]};}
const area=best?best.count/(limit*h):0;return {visible:!!best&&best.count>=16&&area<.55,total,area,...best,reason:area>=.55?'颜色覆盖背景过多，请换一种对比更明显的颜色。':(!best||best.count<16)?'未找到足够大的连续色块：请靠近、补光或重新选色。':''};}
const api={hsv,hueDistance,pick,detect};if(typeof module!=='undefined')module.exports=api;else root.ColorTracker=api;
})(typeof window!=='undefined'?window:globalThis);
